services:
  mysql:
    image: mysql
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/mysql
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"